name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: src/Overlay.API
      - name: Build
        run: dotnet publish -c Release -o release
        working-directory: src/Overlay.API
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: src/Overlay.API/release/*
